name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
      
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          chmod +x /path/to/your/deploy.sh
          /path/to/your/deploy.sh
